item-info-type:
  tool: [WOODEN_SHOVEL, WOODEN_PICKAXE, WOODEN_AXE, WOODEN_HOE,
         STONE_SHOVEL, STONE_PICKAXE, WOODEN_AXE, STONE_HOE,
         IRON_SHOVEL, IRON_PICKAXE, IRON_AXE, IRON_HOE,
         GOLDEN_SHOVEL, GOLDEN_PICKAXE, GOLDEN_AXE, GOLDEN_HOE,
         DIAMOND_SHOVEL, DIAMOND_PICKAXE, GOLDEN_AXE, GOLDEN_HOE]
  weapon: [WOODEN_SWORD, STONE_SWORD, IRON_SWORD, GOLDEN_SWORD, DIAMOND_SWORD, BOW, CROSSBOW]
tooltip:
  tool: "Blocks Broken: %d"
  weapon: "Enemies Killed: %d"
help:
  index: "&8&l&m                                  &r\n     Tool Stats Plugin\n     /<command> help\n     /<command> getStats\n     /<command> updateLore\n     /<command> removeLore\n     /<command> removeStats\n&8&l&m                                  &r"
  get-stats: "&8&l&m                                  &r\n     /<command> getStats\n\n      Shows current item stats\n&8&l&m                                  &r"
  update-lore: "&8&l&m                                  &r\n     /<command> updateLore\n\n      Updates item lore\n&8&l&m                                  &r"
  remove-lore: "&8&l&m                                  &r\n     /<command> removeLore\n\n      Removes item lore\n&8&l&m                                  &r"
  remove-stats: "&8&l&m                                  &r\n     /<command> removeStats\n\n      Removes item stats\n&8&l&m                                  &r"
